name: Draft Public Release

on:
  push:
    branches: [release/v*]

jobs:
  build:
    uses: libanvl/uuid/.github/workflows/ci-call.yml@main
    with:
      runs-on: ubuntu-latest
      dotnet-version: 6.0.x
      dotnet-include-prerelease: true
      package: true
  draft_release:
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: nupkg
      - name: Set Tag Version
        run: TAG_VERSION=$(cat ./nupkg/version.txt)
      - name: Draft Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          files: ./nupkg/*.nupkg
          draft: true
          target_commitish: ${{ env.GITHUB_REF }}
          tag_name: v${{ env.TAG_VERSION }}
          fail_on_unmatched_files: true
